from src.database.update_table_analysis_info_revenue_sp500 import insert_updated_analysis_info_revenue_data_into_db

insert_updated_analysis_info_revenue_data_into_db()
print('complete analysis info revenue sp500')
